alias grep="grep --color"
alias ls="exa --icons --group-directories-first --color=always --git"
alias cat="batcat"
alias cd="zoxide"
alias dotfiles="ansible-playbook -K ~/dotfiles/bootstrap.yml && bash"