---
- name: "Code: Check if installed"
  when: ansible_distribution == "Debian"
  shell: command -v code
  register: go_exist
  ignore_errors: true

- name: "Code: Install linux"
  become: true
  ansible.builtin.apt:
    deb: https://vscode.download.prss.microsoft.com/dbazure/download/stable/dc96b837cf6bb4af9cd736aa3af08cf8279f7685/code_{{ code_version }}_amd64.deb
  when: ansible_facts['distribution'] == 'Debian' and ansible_facts['virtualization_type']!= 'windows' and go_exist is failed

- name: "Code: Install windows"
  when: ansible_distribution == "Windows"
  win_chocolatey:
    name: "vscode"
    state: present

- name: "Code: Copy conf linux"
  when: ansible_distribution == "Debian"
  copy:
    src: /home/debian/dotfiles/Code
    dest: ~/.config

- name: "Code: Copy conf windows"
  when: ansible_distribution == "Windows"
  copy:
    src: C:\Users\pcabo\dotfiles\Code\User\settings.json
    dest: C:\Users\pcabo\AppData\Roaming\Code\User\settings.json

- name: "Code: Install Extensions"
  loop:
    - aaron-bond.better-comments
    - batisteo.vscode-django
    - berublan.vscode-log-viewer
    - codezombiech.gitignore
    - donjayamanne.githistory
    - donjayamanne.python-environment-manager
    - donjayamanne.python-extension-pack
    - eamodio.gitlens
    - formulahendry.code-runner
    - gitlab.gitlab-workflow
    - golang.go
    - howardzuo.vscode-git-tags
    - kevinrose.vsc-python-indent
    - mechatroner.rainbow-csv
    - mhutchie.git-graph
    - ms-azuretools.vscode-docker
    - ms-python.black-formatter
    - ms-python.debugpy
    - ms-python.pylint
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-vscode-remote.remote-wsl
    - njpwerner.autodocstring
    - redhat.ansible
    - redhat.vscode-yaml
    - rust-lang.rust-analyzer
    - shaharkazaz.git-merger
    - shan.code-settings-sync
    - shyykoserhiy.git-autoconfig
    - stuart.unique-window-colors
    - tal7aouy.theme
    - tamasfe.even-better-toml
    - techiecouch.git-essentials
    - vadimcn.vscode-lldb
    - visualstudioexptteam.intellicode-api-usage-examples
    - visualstudioexptteam.vscodeintellicode
    - waderyan.gitblame
    - wholroyd.jinja
    - yzhang.markdown-all-in-one
    - zainchen.json
    - ziyasal.vscode-open-in-github
  command: "code --install-extension {{ item }}"


