- name: Install VSCode extensions
  hosts: vscode
  become: yes
  roles:
    - role: gantsign.visual-studio-code
      users:
        - username: f9mc
          visual_studio_code_extensions:
            - aaron-bond.better-comments
            - berublan.vscode-log-viewer
            - codezombiech.gitignore
            - cweijan.dbclient-jdbc
            - cweijan.vscode-database-client2
            - denco.confluence-markup
            - donjayamanne.githistory
            - eamodio.gitlens
            - euskadi31.json-pretty-printer
            - gitlab.gitlab-workflow
            - gruntfuggly.todo-tree
            - howardzuo.vscode-git-tags
            - mechatroner.rainbow-csv
            - mhutchie.git-graph
            - ms-azuretools.vscode-docker
            - ms-python.black-formatter
            - ms-python.debugpy
            - ms-python.pylint
            - ms-python.python
            - ms-python.vscode-pylance
            - ms-vscode.powershell
            - perragnaredin.light-plus-tweaked
            - redhat.vscode-yaml
            - shaharkazaz.git-merger
            - shan.code-settings-sync
            - shyykoserhiy.git-autoconfig
            - sldobri.bunker
            - stuart.unique-window-colors
            - tal7aouy.theme
            - techiecouch.git-essentials
            - waderyan.gitblame
            - wholroyd.jinja
            - yzhang.markdown-all-in-one
            - zhuangtongfa.material-theme
            - ziyasal.vscode-open-in-github
