---
- name: "Font: Create a directory for the font"
  file:
    path: /usr/local/share/fonts
    state: directory

- name: "Font: Download the font"
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/0xProto.zip
    dest: /usr/local/share/fonts/0xProto.zip

- name: "Font: Unzip the font"
  unarchive:
    src: /usr/local/share/fonts/0xProto.zip
    dest: /usr/local/share/fonts/
    remote_src: yes

- name: "Font: Update font cache"
  command: fc-cache -f -v