---
- name: "Debian: Install packages with apt"
  become: true
  become_user: root
  ansible.builtin.apt:
    name:
      - git
      - exa
      - curl
      - wget
      - ansible-lint
      - vim
      - meld
      - zsh
      - tmux
      - bat
      - zoxide
    state: present
  when: ansible_distribution == "Debian"

- name: "Debian: Copy dotfiles"
  loop:
    - .bashrc.d
    - .bashrc
    - .zshrc.d
    - .zshrc
    - .gitconfig
    - .gitignore_global
    - .tmux.conf
  ansible.builtin.copy:
    src: /home/debian/dotfiles/{{ item }}
    dest: ~/
    owner: debian
    group: debian
    mode: '0744'

- name: "Debian: Remove useless directories"
  loop:
    - Modèles
    - Musique
    - Vidéos
    - Public
    - Images
  ansible.builtin.file:
    path: /home/debian/{{ item }}
    state: absent

- name: "Debian: gnome setup"
  when: ansible_env.DESKTOP_SESSION == "gnome"
  import_tasks: gnome.yml
  ignore_errors: true

- name: "Debian: zsh setup"
  import_tasks: zsh.yml

- name: "Tmux: install plugins"
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: ~/.tmux/plugins/tpm
    depth: 1
