---
- namme: "Debian: set user as a sudoers"
  ansible.builtin.user:
    name: debian
    groups: sudoers
    append: yes

- name: "Debian: Install packages with apt"
  become: true
  become_user: root
  ansible.builtin.apt:
    name:
      - git
      - exa
      - curl
      - wget
    state: present
  when: ansible_distribution == "Debian"

- name: "Debian: Copy dotfiles"
  become: true
  become_user: debian
  loop:
    - .bashrc.d
    - .bashrc
    - .gitconfig
  copy:
    src: /home/debian/dotfiles/{{ item }}
    dest: ~/
