---
- name: "Debian: Install packages with apt"
  become: true
  become_user: root
  ansible.builtin.apt:
    name:
      - git
      - exa
      - curl
      - wget
      - vim
      - zsh
      - tmux
      - zoxide
      - fzf
    state: present
  

- name: "Debian: Copy dotfiles"
  loop:
    - .bashrc.d
    - .bashrc
    - .zshrc.d
    - .zshrc
    - .gitconfig
    - .gitignore_global
    - .tmux.conf
  ansible.builtin.copy:
    src: /home/debian/dotfiles/{{ item }}
    dest: ~/
    owner: debian
    group: debian
    mode: '0744'

- name: "Debian: Remove useless directories"
  loop:
    - Modèles
    - Musique
    - Vidéos
    - Public
    - Images
  ansible.builtin.file:
    path: /home/debian/{{ item }}
    state: absent

- name: "Debian: zsh setup"
  import_tasks: zsh.yml

- name: "Debian: font install"
  import_tasks: font.yml