---
- name: "Debian: Install packages with apt"
  become: true
  become_user: root
  ansible.builtin.apt:
    name:
      - git
      - exa
      - curl
      - wget
    state: present
  when: ansible_distribution == "Debian"

- name: "Debian: Copy dotfiles"
  loop:
    - .bashrc.d
    - .bashrc
    - .gitconfig
  ansible.builtin.copy:
    src: /home/debian/dotfiles/{{ item }}
    dest: ~/
    owner: debian
    group: debian
    mode: '0744'

- name: "Debian: Remove useless directories"
  loop:
    - Modèles
    - Musique
    - Vidéos
    - Public
  ansible.builtin.file:
    path: /home/debian/{{ item }}
    state: absent

- name: "Debian: gnome setup"
  when: ansible_facts['distribution'] == 'Debian' and ansible_facts['virtualization_type']!= 'windows'
  ansible.builtin.import_role:
    name: gnome
