---
- name: "GO: check if go is installed"
  become: true
  become_user: debian
  shell: command -v go
  register: go_exist
  ignore_errors: true

- name: "Go: download installer"
  become: true
  become_user: debian
  command: wget https://go.dev/dl/go{{go_version}}.linux-amd64.tar.gz
  when: go_exist is failed

- name: "Go: remove previous install"
  command: rm -rf /usr/local/go
  become: true
  when: go_exist is failed

- name: "Go: extract new"
  command: tar -C /usr/local -xzf go{{go_version}}.linux-amd64.tar.gz
  become: true
  when: go_exist is failed

- name: "Go: remove installation files"
  become: true
  become_user: debian
  shell: rm -rf go{{go_version}}.linux-amd64.tar.gz*
  when: go_exist is failed
