---
- name: "Python: Install"
  become: true
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
    state: present

- name: "Python: Remove EXTERNALLY-MANAGED file"
  become: true
  ansible.builtin.file:
    path: /usr/lib/python3.11/EXTERNALLY-MANAGED
    state: absent

- name: "Python: Install python package"
  become: true
  become_user: debian
  loop:
    - black
    - pyyaml
  ansible.builtin.pip:
    name: "{{ item }}"
