---
- name: "Rust: download installer"

  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: "0755"
    force: "yes"

- name: "Rust: Install"

  shell: /tmp/sh.rustup.rs -y

- name: "Rust: Install windows"
  when: ansible_distribution == "Windows"
  win_chocolatey:
    name: "rust"
    state: present
